#try catch example.  Adding two numbers and name error occurs
try:
    num=10
    nun=20
    res=num+sun
except:
    print('An error has occured')
print('Program completed')
    
